import type { ContributionStats, StationChange } from "$lib/types/contribution";

function generateGoogleMapsLink(lat: number, lng: number): string {
  return `https://www.google.com/maps?q=${lat},${lng}`;
}

function generateRfiLink(stationId: string): string {
  return `https://iechub.rfi.it/ArriviPartenze/en/ArrivalsDepartures/Monitor?placeId=${stationId}&arrivals=False`;
}

function getTypeBadge(type: StationChange["type"]): string {
  switch (type) {
    case "created":
      return "Added";
    case "updated":
      return "Changed";
    case "deleted":
      return "Removed";
    default:
      return "Changed";
  }
}

export function generatePRTitle(stats: ContributionStats): string {
  const parts: string[] = [];

  if (stats.coordinatesUpdated > 0) {
    parts.push(
      `update ${stats.coordinatesUpdated} coordinate${stats.coordinatesUpdated !== 1 ? "s" : ""}`,
    );
  }
  if (stats.stationsRenamed > 0) {
    parts.push(`rename ${stats.stationsRenamed} station${stats.stationsRenamed !== 1 ? "s" : ""}`);
  }
  if (stats.stationsCreated > 0) {
    parts.push(`create ${stats.stationsCreated} station${stats.stationsCreated !== 1 ? "s" : ""}`);
  }
  if (stats.stationsDeleted > 0) {
    parts.push(`delete ${stats.stationsDeleted} station${stats.stationsDeleted !== 1 ? "s" : ""}`);
  }

  return parts.length === 0 ? "feat(data): update station data" : `feat(data): ${parts.join(", ")}`;
}

function formatChangeDescription(change: StationChange): {
  details: string;
  mapLink: string | null;
} {
  const { type, details } = change;

  if (type === "created") {
    if (details.newGeo) {
      return {
        details: `Created at (${details.newGeo.lat.toFixed(4)}, ${details.newGeo.lng.toFixed(4)})`,
        mapLink: generateGoogleMapsLink(details.newGeo.lat, details.newGeo.lng),
      };
    }
    return { details: "Created", mapLink: null };
  }

  if (type === "deleted") {
    return { details: "Deleted", mapLink: null };
  }

  const updates: string[] = [];
  let mapLink: string | null = null;

  if (details.coordinatesUpdated && details.newGeo) {
    updates.push(`Moved to (${details.newGeo.lat.toFixed(4)}, ${details.newGeo.lng.toFixed(4)})`);
    mapLink = generateGoogleMapsLink(details.newGeo.lat, details.newGeo.lng);
  }
  if (details.nameChanged && details.previousName) {
    updates.push(`Renamed from "${details.previousName}"`);
  }
  if (details.typeChanged && details.previousType && details.newType) {
    updates.push(`Type changed from ${details.previousType} to ${details.newType}`);
  }
  if (
    details.importanceChanged &&
    details.previousImportance !== undefined &&
    details.newImportance !== undefined
  ) {
    updates.push(
      `Importance changed from ${details.previousImportance} to ${details.newImportance}`,
    );
  }

  return { details: updates.join(", ") || "Updated", mapLink };
}

export function generatePRBody(changes: StationChange[], stats: ContributionStats): string {
  const lines: string[] = [];
  const summaryParts: string[] = [];

  lines.push("## Summary");
  if (stats.coordinatesUpdated > 0) {
    summaryParts.push(
      `Updated coordinates for ${stats.coordinatesUpdated} station${stats.coordinatesUpdated !== 1 ? "s" : ""}`,
    );
  }
  if (stats.stationsRenamed > 0) {
    summaryParts.push(
      `Renamed ${stats.stationsRenamed} station${stats.stationsRenamed !== 1 ? "s" : ""}`,
    );
  }
  if (stats.stationsCreated > 0) {
    summaryParts.push(
      `Created ${stats.stationsCreated} new station${stats.stationsCreated !== 1 ? "s" : ""}`,
    );
  }
  if (stats.stationsDeleted > 0) {
    summaryParts.push(
      `Deleted ${stats.stationsDeleted} station${stats.stationsDeleted !== 1 ? "s" : ""}`,
    );
  }

  lines.push(`${summaryParts.join(". ")}.`);
  lines.push("");
  lines.push("## Changes");
  lines.push("| Station | Type | Details | Map | RFI |");
  lines.push("|---------|------|---------|-----|-----|");

  for (const change of changes) {
    const { details, mapLink } = formatChangeDescription(change);
    const mapCell = mapLink ? `[View](${mapLink})` : "-";
    const rfiCell = change.type !== "deleted" ? `[Check](${generateRfiLink(change.id)})` : "-";
    lines.push(
      `| ${change.stationName} | ${getTypeBadge(change.type)} | ${details} | ${mapCell} | ${rfiCell} |`,
    );
  }

  lines.push("");
  lines.push("---");
  lines.push("*Generated by Rail Radar Studio*");

  return lines.join("\n");
}
