/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PrivacyPolicyRouteImport } from "./routes/privacy-policy";
import { Route as SitemapDotxmlRouteImport } from "./routes/sitemap[.]xml";
import { Route as TermsOfServiceRouteImport } from "./routes/terms-of-service";
import { Route as DonateIndexRouteImport } from "./routes/donate/index";
import { Route as DonateSuccessRouteImport } from "./routes/donate/success";
import { Route as MediaOgRouteImport } from "./routes/media/og";
import { Route as OperatorsIndexRouteImport } from "./routes/operators/index";
import { Route as OperatorsSlugRouteImport } from "./routes/operators/$slug";
import { Route as Report20260428RouteImport } from "./routes/report/2026-04-28";
import { Route as Report20260724RouteImport } from "./routes/report/2026-07-24";
import { Route as StationIdRouteImport } from "./routes/station/$id";
import { Route as StationsIndexRouteImport } from "./routes/stations/index";
import { Route as StationsCountryRouteImport } from "./routes/stations/$country";
import { Route as MediaStationsStationIdPhotosRouteImport } from "./routes/media/stations/$stationId/photos";
import { Route as MediaStationsStationIdPhotoSplatRouteImport } from "./routes/media/stations/$stationId/photo/$";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: "/privacy-policy",
  path: "/privacy-policy",
  getParentRoute: () => rootRouteImport,
} as any);
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: "/sitemap.xml",
  path: "/sitemap.xml",
  getParentRoute: () => rootRouteImport,
} as any);
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: "/terms-of-service",
  path: "/terms-of-service",
  getParentRoute: () => rootRouteImport,
} as any);
const DonateIndexRoute = DonateIndexRouteImport.update({
  id: "/donate/",
  path: "/donate/",
  getParentRoute: () => rootRouteImport,
} as any);
const DonateSuccessRoute = DonateSuccessRouteImport.update({
  id: "/donate/success",
  path: "/donate/success",
  getParentRoute: () => rootRouteImport,
} as any);
const MediaOgRoute = MediaOgRouteImport.update({
  id: "/media/og",
  path: "/media/og",
  getParentRoute: () => rootRouteImport,
} as any);
const OperatorsIndexRoute = OperatorsIndexRouteImport.update({
  id: "/operators/",
  path: "/operators/",
  getParentRoute: () => rootRouteImport,
} as any);
const OperatorsSlugRoute = OperatorsSlugRouteImport.update({
  id: "/operators/$slug",
  path: "/operators/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const Report20260428Route = Report20260428RouteImport.update({
  id: "/report/2026-04-28",
  path: "/report/2026-04-28",
  getParentRoute: () => rootRouteImport,
} as any);
const Report20260724Route = Report20260724RouteImport.update({
  id: "/report/2026-07-24",
  path: "/report/2026-07-24",
  getParentRoute: () => rootRouteImport,
} as any);
const StationIdRoute = StationIdRouteImport.update({
  id: "/station/$id",
  path: "/station/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const StationsIndexRoute = StationsIndexRouteImport.update({
  id: "/stations/",
  path: "/stations/",
  getParentRoute: () => rootRouteImport,
} as any);
const StationsCountryRoute = StationsCountryRouteImport.update({
  id: "/stations/$country",
  path: "/stations/$country",
  getParentRoute: () => rootRouteImport,
} as any);
const MediaStationsStationIdPhotosRoute = MediaStationsStationIdPhotosRouteImport.update({
  id: "/media/stations/$stationId/photos",
  path: "/media/stations/$stationId/photos",
  getParentRoute: () => rootRouteImport,
} as any);
const MediaStationsStationIdPhotoSplatRoute = MediaStationsStationIdPhotoSplatRouteImport.update({
  id: "/media/stations/$stationId/photo/$",
  path: "/media/stations/$stationId/photo/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/privacy-policy": typeof PrivacyPolicyRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/terms-of-service": typeof TermsOfServiceRoute;
  "/donate/success": typeof DonateSuccessRoute;
  "/media/og": typeof MediaOgRoute;
  "/operators/$slug": typeof OperatorsSlugRoute;
  "/report/2026-04-28": typeof Report20260428Route;
  "/report/2026-07-24": typeof Report20260724Route;
  "/station/$id": typeof StationIdRoute;
  "/stations/$country": typeof StationsCountryRoute;
  "/donate/": typeof DonateIndexRoute;
  "/operators/": typeof OperatorsIndexRoute;
  "/stations/": typeof StationsIndexRoute;
  "/media/stations/$stationId/photos": typeof MediaStationsStationIdPhotosRoute;
  "/media/stations/$stationId/photo/$": typeof MediaStationsStationIdPhotoSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/privacy-policy": typeof PrivacyPolicyRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/terms-of-service": typeof TermsOfServiceRoute;
  "/donate/success": typeof DonateSuccessRoute;
  "/media/og": typeof MediaOgRoute;
  "/operators/$slug": typeof OperatorsSlugRoute;
  "/report/2026-04-28": typeof Report20260428Route;
  "/report/2026-07-24": typeof Report20260724Route;
  "/station/$id": typeof StationIdRoute;
  "/stations/$country": typeof StationsCountryRoute;
  "/donate": typeof DonateIndexRoute;
  "/operators": typeof OperatorsIndexRoute;
  "/stations": typeof StationsIndexRoute;
  "/media/stations/$stationId/photos": typeof MediaStationsStationIdPhotosRoute;
  "/media/stations/$stationId/photo/$": typeof MediaStationsStationIdPhotoSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/privacy-policy": typeof PrivacyPolicyRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/terms-of-service": typeof TermsOfServiceRoute;
  "/donate/success": typeof DonateSuccessRoute;
  "/media/og": typeof MediaOgRoute;
  "/operators/$slug": typeof OperatorsSlugRoute;
  "/report/2026-04-28": typeof Report20260428Route;
  "/report/2026-07-24": typeof Report20260724Route;
  "/station/$id": typeof StationIdRoute;
  "/stations/$country": typeof StationsCountryRoute;
  "/donate/": typeof DonateIndexRoute;
  "/operators/": typeof OperatorsIndexRoute;
  "/stations/": typeof StationsIndexRoute;
  "/media/stations/$stationId/photos": typeof MediaStationsStationIdPhotosRoute;
  "/media/stations/$stationId/photo/$": typeof MediaStationsStationIdPhotoSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/privacy-policy"
    | "/sitemap.xml"
    | "/terms-of-service"
    | "/donate/success"
    | "/media/og"
    | "/operators/$slug"
    | "/report/2026-04-28"
    | "/report/2026-07-24"
    | "/station/$id"
    | "/stations/$country"
    | "/donate/"
    | "/operators/"
    | "/stations/"
    | "/media/stations/$stationId/photos"
    | "/media/stations/$stationId/photo/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/privacy-policy"
    | "/sitemap.xml"
    | "/terms-of-service"
    | "/donate/success"
    | "/media/og"
    | "/operators/$slug"
    | "/report/2026-04-28"
    | "/report/2026-07-24"
    | "/station/$id"
    | "/stations/$country"
    | "/donate"
    | "/operators"
    | "/stations"
    | "/media/stations/$stationId/photos"
    | "/media/stations/$stationId/photo/$";
  id:
    | "__root__"
    | "/"
    | "/privacy-policy"
    | "/sitemap.xml"
    | "/terms-of-service"
    | "/donate/success"
    | "/media/og"
    | "/operators/$slug"
    | "/report/2026-04-28"
    | "/report/2026-07-24"
    | "/station/$id"
    | "/stations/$country"
    | "/donate/"
    | "/operators/"
    | "/stations/"
    | "/media/stations/$stationId/photos"
    | "/media/stations/$stationId/photo/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute;
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute;
  TermsOfServiceRoute: typeof TermsOfServiceRoute;
  DonateSuccessRoute: typeof DonateSuccessRoute;
  MediaOgRoute: typeof MediaOgRoute;
  OperatorsSlugRoute: typeof OperatorsSlugRoute;
  Report20260428Route: typeof Report20260428Route;
  Report20260724Route: typeof Report20260724Route;
  StationIdRoute: typeof StationIdRoute;
  StationsCountryRoute: typeof StationsCountryRoute;
  DonateIndexRoute: typeof DonateIndexRoute;
  OperatorsIndexRoute: typeof OperatorsIndexRoute;
  StationsIndexRoute: typeof StationsIndexRoute;
  MediaStationsStationIdPhotosRoute: typeof MediaStationsStationIdPhotosRoute;
  MediaStationsStationIdPhotoSplatRoute: typeof MediaStationsStationIdPhotoSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy-policy": {
      id: "/privacy-policy";
      path: "/privacy-policy";
      fullPath: "/privacy-policy";
      preLoaderRoute: typeof PrivacyPolicyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sitemap.xml": {
      id: "/sitemap.xml";
      path: "/sitemap.xml";
      fullPath: "/sitemap.xml";
      preLoaderRoute: typeof SitemapDotxmlRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/terms-of-service": {
      id: "/terms-of-service";
      path: "/terms-of-service";
      fullPath: "/terms-of-service";
      preLoaderRoute: typeof TermsOfServiceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/donate/": {
      id: "/donate/";
      path: "/donate";
      fullPath: "/donate/";
      preLoaderRoute: typeof DonateIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/donate/success": {
      id: "/donate/success";
      path: "/donate/success";
      fullPath: "/donate/success";
      preLoaderRoute: typeof DonateSuccessRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/media/og": {
      id: "/media/og";
      path: "/media/og";
      fullPath: "/media/og";
      preLoaderRoute: typeof MediaOgRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/operators/": {
      id: "/operators/";
      path: "/operators";
      fullPath: "/operators/";
      preLoaderRoute: typeof OperatorsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/operators/$slug": {
      id: "/operators/$slug";
      path: "/operators/$slug";
      fullPath: "/operators/$slug";
      preLoaderRoute: typeof OperatorsSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/report/2026-04-28": {
      id: "/report/2026-04-28";
      path: "/report/2026-04-28";
      fullPath: "/report/2026-04-28";
      preLoaderRoute: typeof Report20260428RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/report/2026-07-24": {
      id: "/report/2026-07-24";
      path: "/report/2026-07-24";
      fullPath: "/report/2026-07-24";
      preLoaderRoute: typeof Report20260724RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/station/$id": {
      id: "/station/$id";
      path: "/station/$id";
      fullPath: "/station/$id";
      preLoaderRoute: typeof StationIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/stations/": {
      id: "/stations/";
      path: "/stations";
      fullPath: "/stations/";
      preLoaderRoute: typeof StationsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/stations/$country": {
      id: "/stations/$country";
      path: "/stations/$country";
      fullPath: "/stations/$country";
      preLoaderRoute: typeof StationsCountryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/media/stations/$stationId/photos": {
      id: "/media/stations/$stationId/photos";
      path: "/media/stations/$stationId/photos";
      fullPath: "/media/stations/$stationId/photos";
      preLoaderRoute: typeof MediaStationsStationIdPhotosRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/media/stations/$stationId/photo/$": {
      id: "/media/stations/$stationId/photo/$";
      path: "/media/stations/$stationId/photo/$";
      fullPath: "/media/stations/$stationId/photo/$";
      preLoaderRoute: typeof MediaStationsStationIdPhotoSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  DonateSuccessRoute: DonateSuccessRoute,
  MediaOgRoute: MediaOgRoute,
  OperatorsSlugRoute: OperatorsSlugRoute,
  Report20260428Route: Report20260428Route,
  Report20260724Route: Report20260724Route,
  StationIdRoute: StationIdRoute,
  StationsCountryRoute: StationsCountryRoute,
  DonateIndexRoute: DonateIndexRoute,
  OperatorsIndexRoute: OperatorsIndexRoute,
  StationsIndexRoute: StationsIndexRoute,
  MediaStationsStationIdPhotosRoute: MediaStationsStationIdPhotosRoute,
  MediaStationsStationIdPhotoSplatRoute: MediaStationsStationIdPhotoSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
