name: "✨ Feature Request"
description: "Suggest a new feature or enhancement"
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement!

  - type: input
    id: title
    attributes:
      label: Feature title
      placeholder: e.g., “Support dark mode”

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature needed?
      description: What problem does this solve?

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe how this could work

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other options you considered
