// Brand logos come from the web app (apps/web/public/assets/operators), which serves them.
// A copy of the web's mapping in apps/web/src/components/brands.tsx.
const brandPaths: Record<string, string> = {
  // Italian brands
  trenitalia: "it/trenitalia",
  regionale: "it/regionale",
  intercity: "it/intercity",
  "intercity notte": "it/intercity_notte",
  italo: "it/italo",
  frecciarossa: "it/frecciarossa",
  trenord: "it/trenord",
  "trenitalia tper": "it/tper",
  sad: "it/sad",
  tua: "it/tua",
  // Swiss brands
  bls: "ch/bls",
  sbb: "ch/sbb",
  sob: "ch/sob",
  szu: "ch/szu",
  rbs: "ch/rbs",
  tpf: "ch/tpf",
  zb: "ch/zb",
  ab: "ch/ab",
  thurbo: "ch/thurbo",
  tpc: "ch/tpc",
  tmr: "ch/tmr",
  mgb: "ch/mgb",
  ra: "ch/ra",
  rhb: "ch/rhb",
  mob: "ch/mob",
  flp: "ch/flp",
  // Other
  obb: "obb",
  cfl: "cfl",
  // French brands (SNCF networks)
  sncf: "fr/sncf",
  "tgv inoui": "fr/inoui",
  ouigo: "fr/ouigo",
  lex: "fr/leman",
  rer: "fr/rer",
  transilien: "fr/transilien",
  ter: "fr/ter",
  "tgv lyria": "fr/lyria",
  // Regional TER networks with their own liveries
  fluo: "fr/fluo",
  regionaura: "fr/regionaura",
  "ter na": "fr/ter-na",
  "zou !": "fr/zou",
  vr: "vr",
  sncb: "sncb",
  eurostar: "eurostar",
  arriva: "arriva",
  dsb: "dk/dsb",
  lokaltog: "dk/lokaltog",
  nj: "dk/nj",
  "midtjyske jernbaner": "dk/mj",
  øresundståg: "dk/oresundstag",
  oresundstag: "dk/oresundstag",
  skånetrafiken: "dk/ska",
  skanetrafiken: "dk/ska",
  db: "de/db",
  flixtrain: "de/flixtrain",
  hlb: "de/hlb",
  odeg: "de/odeg",
  stb: "de/stb",
  vias: "de/vias",
  westfalenbahn: "de/westfalenbahn",
  vogtlandbahn: "de/vogtlandbahn",
  ns: "ns",
  vy: "no/vy",
  "sj nord": "no/sj_nord",
  // Polish brands
  "pkp intercity": "pl/pkp-intercity",
  polregio: "pl/polregio",
  kd: "pl/kd",
  "koleje dolnośląskie": "pl/kd",
  "koleje dolnoslaskie": "pl/kd",
  km: "pl/km",
  kml: "pl/kml",
  kmł: "pl/kml",
  "koleje małopolskie": "pl/kml",
  "koleje malopolskie": "pl/kml",
  ks: "pl/ks",
  kw: "pl/kw",
  skm: "pl/skm",
  łka: "pl/lka",
  "warszawska kolej dojazdowa": "pl/wkd",
  railpolonia: "pl/railpolonia",
  "leo express": "leo-express",
  regiojet: "regiojet",
  // Swedish brands
  sj: "se/sj",
  "arlanda express": "se/arlanda",
  mälartåg: "se/malartag",
  malartag: "se/malartag",
  västtrafik: "se/vasttrafik",
  vasttrafik: "se/vasttrafik",
  "mtr express": "se/mtr",
  snälltåget: "se/snalltaget",
  transdev: "transdev",
  "go-ahead norge": "no/go_ahead",
  flytoget: "no/flytoget",
  // UK brands
  lm: "uk/lm",
  nt: "uk/nt",
  gw: "uk/gw",
  xc: "uk/xc",
  sr: "uk/sr",
  em: "uk/em",
  se: "uk/se",
  sw: "uk/sw",
  sn: "uk/sn",
  le: "uk/le",
  gr: "uk/gr",
  xr: "uk/xr",
  tl: "uk/tl",
  ch: "uk/ch",
  vt: "uk/vt",
  aw: "uk/aw",
  tp: "uk/tp",
  lo: "uk/lo",
  cc: "uk/cc",
  cs: "uk/cs",
  gc: "uk/gc",
  ht: "uk/ht",
  // Irish brands
  ir: "ir",
};

// Aliases for brands that share icons
const brandAliases: Record<string, string> = {
  ntv: "italo",
  frecciabianca: "trenitalia",
  frecciargento: "trenitalia",
  fse: "trenitalia",
  "leonardo express": "trenitalia",
  "obb railjet": "obb",
  "obb nightjet": "obb",
  "sbb gmbh": "sbb",
  es: "eurostar",
  "ouigo train classique": "ouigo",
  // DB-SNCF cooperation runs both ICE and TGV; show the DB mark as a stand-in.
  "db sncf": "db",
  // Intercités is its own brand but has no dedicated logo — fall back to SNCF.
  intercités: "sncf",
  intercites: "sncf",
  // Regional TER networks with their own logos
  "ter fluo": "fluo",
  zou: "zou !",
  // Regional TER declensions without a dedicated logo share the unified TER logo
  "ter hdf": "ter",
  nomad: "ter",
  rémi: "ter",
  remi: "ter",
  lio: "ter",
  mobigo: "ter",
  breizhgo: "ter",
  aléop: "ter",
  aleop: "ter",
  gn: "tl",
  gx: "sn",
  ln: "lm",
  wm: "lm",
  "go-ahead": "go-ahead norge",
  "go-ahead nordic": "go-ahead norge",
  sjn: "sj nord",
  "go-ahead norge as": "go-ahead norge",
  "go-ahead nordic as": "go-ahead norge",
  oresundstag: "øresundståg",
  skanetrafiken: "skånetrafiken",
};

const logoBaseUrl = "https://www.railradar24.com/assets/operators";

/** The URL of a brand's SVG logo, or null when there is none. */
export function getBrandLogoUrl(brand: string): string | null {
  const normalized = brand.toLowerCase();
  const path = brandPaths[brandAliases[normalized] ?? normalized];
  return path ? `${logoBaseUrl}/${path}.svg` : null;
}
