import type { StationChange, ContributionStats } from "../types/contribution";

export function generatePRTitle(stats: ContributionStats): string {
  const parts: string[] = [];

  if (stats.coordinatesAdded > 0) {
    parts.push(
      `add ${stats.coordinatesAdded} coordinate${stats.coordinatesAdded !== 1 ? "s" : ""}`
    );
  }

  if (stats.coordinatesUpdated > 0) {
    parts.push(
      `update ${stats.coordinatesUpdated} coordinate${stats.coordinatesUpdated !== 1 ? "s" : ""}`
    );
  }

  if (stats.stationsRenamed > 0) {
    parts.push(
      `rename ${stats.stationsRenamed} station${stats.stationsRenamed !== 1 ? "s" : ""}`
    );
  }

  if (stats.stationsCreated > 0) {
    parts.push(
      `create ${stats.stationsCreated} station${stats.stationsCreated !== 1 ? "s" : ""}`
    );
  }

  if (stats.stationsDeleted > 0) {
    parts.push(
      `delete ${stats.stationsDeleted} station${stats.stationsDeleted !== 1 ? "s" : ""}`
    );
  }

  if (parts.length === 0) {
    return "feat(data): update station data";
  }

  return `feat(data): ${parts.join(", ")}`;
}

function formatChangeDescription(change: StationChange): string {
  const { type, details } = change;

  if (type === "created") {
    if (details.newGeo) {
      return `Created with coordinates (${details.newGeo.lat.toFixed(4)}, ${details.newGeo.lng.toFixed(4)})`;
    }
    return "Created";
  }

  if (type === "deleted") {
    return "Deleted";
  }

  // Updated
  const updates: string[] = [];

  if (details.coordinatesAdded && details.newGeo) {
    updates.push(
      `Added coordinates (${details.newGeo.lat.toFixed(4)}, ${details.newGeo.lng.toFixed(4)})`
    );
  } else if (details.coordinatesUpdated && details.newGeo) {
    updates.push(
      `Updated coordinates to (${details.newGeo.lat.toFixed(4)}, ${details.newGeo.lng.toFixed(4)})`
    );
  }

  if (details.nameChanged && details.previousName && details.newName) {
    updates.push(`Renamed from "${details.previousName}"`);
  }

  return updates.join(", ") || "Updated";
}

export function generatePRBody(
  changes: StationChange[],
  stats: ContributionStats
): string {
  const lines: string[] = [];

  // Summary
  lines.push("## Summary");
  const summaryParts: string[] = [];

  if (stats.coordinatesAdded > 0) {
    summaryParts.push(
      `Added coordinates for ${stats.coordinatesAdded} station${stats.coordinatesAdded !== 1 ? "s" : ""}`
    );
  }
  if (stats.coordinatesUpdated > 0) {
    summaryParts.push(
      `Updated coordinates for ${stats.coordinatesUpdated} station${stats.coordinatesUpdated !== 1 ? "s" : ""}`
    );
  }
  if (stats.stationsRenamed > 0) {
    summaryParts.push(
      `Renamed ${stats.stationsRenamed} station${stats.stationsRenamed !== 1 ? "s" : ""}`
    );
  }
  if (stats.stationsCreated > 0) {
    summaryParts.push(
      `Created ${stats.stationsCreated} new station${stats.stationsCreated !== 1 ? "s" : ""}`
    );
  }
  if (stats.stationsDeleted > 0) {
    summaryParts.push(
      `Deleted ${stats.stationsDeleted} station${stats.stationsDeleted !== 1 ? "s" : ""}`
    );
  }

  lines.push(summaryParts.join(". ") + ".");
  lines.push("");

  // Changes table
  lines.push("## Changes");
  lines.push("| Station | Change |");
  lines.push("|---------|--------|");

  for (const change of changes) {
    const description = formatChangeDescription(change);
    lines.push(`| ${change.stationName} | ${description} |`);
  }

  lines.push("");

  // Stats
  lines.push("## Stats");
  const coverageChange = stats.currentCoverage - stats.initialCoverage;
  const coverageChangeText =
    coverageChange > 0
      ? ` (+${coverageChange.toFixed(1)}%)`
      : coverageChange < 0
        ? ` (${coverageChange.toFixed(1)}%)`
        : "";

  lines.push(
    `- Coverage: ${stats.initialCoverage.toFixed(1)}% -> ${stats.currentCoverage.toFixed(1)}%${coverageChangeText}`
  );
  lines.push("");

  // Footer
  lines.push("---");
  lines.push("*Generated by Rail Radar Studio*");

  return lines.join("\n");
}

export function generateGitHubPRUrl(
  owner: string,
  repo: string,
  title: string,
  body: string,
  baseBranch = "main"
): string {
  const params = new URLSearchParams({
    title,
    body,
    base: baseBranch,
  });

  return `https://github.com/${owner}/${repo}/compare/${baseBranch}...HEAD?${params.toString()}`;
}
